export const INSTALLATIONS_DATA = [
  {
    slug: "piscina",
    title: "Piscina Privada",
    headline: "Un oasis de tranquilidad",
    shortDescription: "Piscina cristalina rodeada de una amplia terraza, perfecta para celebraciones de primavera y verano.",
    fullDescription: "El epicentro de las celebraciones cuando llega el buen tiempo. Nuestra zona de piscina cuenta con un solárium espacioso y vallado de seguridad para la tranquilidad de los padres. Ideal para relajarse durante el día o crear un ambiente mágico y sofisticado por la noche gracias a su iluminación subacuática.",
    heroImage: "/images/real/real-52.webp",
    gallery: [
      "/images/real/real-52.webp",
      "/images/real/real-2.webp",
      "/images/real/real-1.webp",
      "/images/real/real-6.webp",
    ],
    features: [
      "Agua tratada sin químicos agresivos",
      "Iluminación LED nocturna",
      "Zona de solárium y hamacas",
      "Vallado de seguridad infantil",
      "Duchas exteriores",
      "Acceso directo a la terraza",
    ],
    capacity: "Aforo para 30 bañistas",
  },
  {
    slug: "salon",
    title: "Gran Salón",
    headline: "El corazón de tu celebración",
    shortDescription: "Un espacio diáfano, climatizado y versátil, diseñado para banquetes, bailes y reuniones multitudinarias.",
    fullDescription: "El salón principal es el espacio más polivalente de El Corrihuelo. Decorado con un estilo rústico contemporáneo, ofrece el lienzo perfecto para cualquier tipo de evento. Su acústica cuidada, el sistema de climatización y su conexión directa con las zonas exteriores garantizan el éxito de tu celebración en cualquier época del año.",
    heroImage: "/images/real/real-54.webp",
    gallery: [
      "/images/real/real-54.webp",
      "/images/real/real-57.webp",
      "/images/real/real-59.webp",
      "/images/real/real-53.webp",
    ],
    features: [
      "Más de 120 m² diáfanos",
      "Climatización completa (frío/calor)",
      "Sistema de sonido profesional",
      "Iluminación regulable",
      "Decoración rústica moderna",
      "Mesas y sillas incluidas",
    ],
    capacity: "Hasta 100 personas sentadas",
  },
  {
    slug: "zona-gourmet",
    title: "Zona Gourmet",
    headline: "Todo equipado para la buena mesa",
    shortDescription: "Cocina interior completamente equipada, pensada tanto para particulares como para servicios de catering externos.",
    fullDescription: "En El Corrihuelo creemos que la buena mesa es parte esencial de cualquier celebración. Por eso hemos equipado nuestros espacios gastronómicos al máximo nivel. La cocina interior cuenta con electrodomésticos industriales, amplias zonas de trabajo y almacenamiento refrigerado suficiente para grandes eventos.",
    heroImage: "/images/real/real-58.webp",
    gallery: [
      "/images/real/real-58.webp",
      "/images/real/real-59.webp",
      "/images/real/real-54.webp",
      "/images/real/real-1.webp",
    ],
    features: [
      "Cocina interior equipada",
      "Neveras de gran capacidad",
      "Botelleros profesionales",
      "Compatible con servicio de catering",
      "Amplias encimeras de trabajo",
      "Utensilios básicos disponibles",
    ],
    capacity: "Servicio para hasta 100 personas",
  },
  {
    slug: "barbacoa",
    title: "Barbacoa Exterior",
    headline: "El auténtico sabor del fuego",
    shortDescription: "Amplia zona de asados exterior, perfecta para paellas gigantes, parrilladas de carne y reuniones informales al aire libre.",
    fullDescription: "No hay verdadera celebración rústica sin fuego. Nuestra espectacular zona de barbacoa exterior está diseñada para dar servicio a grupos grandes. Está equipada para preparar desde las tradicionales parrilladas de carne murcianas hasta paellas gigantes, todo ello bajo una cómoda zona cubierta que permite cocinar independientemente del clima.",
    heroImage: "/images/real/real-1.webp",
    gallery: [
      "/images/real/real-1.webp",
      "/images/real/real-6.webp",
      "/images/real/real-7.webp",
      "/images/real/real-2.webp",
    ],
    features: [
      "Barbacoa de gran formato",
      "Zona techada para cocinar",
      "Ideal para asados y paellas",
      "Fregadero exterior integrado",
      "Mesas de apoyo cercanas",
      "Uso de leña/carbón permitido",
    ],
    capacity: "Uso simultáneo para grupos",
  },
  {
    slug: "jardines",
    title: "Los Jardines",
    headline: "Naturaleza y privacidad total",
    shortDescription: "Miles de metros cuadrados de jardines cuidados al milímetro. Vegetación autóctona, rincones de descanso y total intimidad.",
    fullDescription: "Los jardines de El Corrihuelo son un universo propio. Con miles de metros cuadrados de naturaleza mediterránea cuidada al detalle, ofrecen espacios diferenciados para cada momento de tu celebración: rincones íntimos para la sobremesa, zonas amplias para el cóctel de bienvenida, y caminos rodeados de flores para pasear al atardecer.",
    heroImage: "/images/real/real-3.webp",
    gallery: [
      "/images/real/real-3.webp",
      "/images/real/real-52.webp",
      "/images/real/real-6.webp",
      "/images/real/real-2.webp",
    ],
    features: [
      "Más de 5.000 m² de parcela",
      "Vegetación autóctona madura",
      "Caminos adoquinados",
      "Iluminación exterior nocturna",
      "Rincones de descanso fotográficos",
      "Privacidad perimetral absoluta",
    ],
    capacity: "Sin límite (espacio exterior)",
  },
  {
    slug: "parque-infantil",
    title: "Parque Infantil",
    headline: "Diversión segura para los más pequeños",
    shortDescription: "Espacio delimitado y seguro con juegos al aire libre para que los niños disfruten mientras los adultos se relajan.",
    fullDescription: "Sabemos que en las celebraciones familiares el entretenimiento infantil es clave. Hemos destinado una zona del jardín a la creación de un parque infantil seguro y divertido. Situado de forma estratégica, permite a los padres tener a los niños a la vista desde los jardines y terrazas mientras disfrutan de la sobremesa.",
    heroImage: "/images/real/real-55.webp",
    gallery: [
      "/images/real/real-55.webp",
      "/images/real/real-2.webp",
      "/images/real/real-52.webp",
      "/images/real/real-3.webp",
    ],
    features: [
      "Estructuras de juego exterior",
      "Suelo de seguridad/césped",
      "Zonas de sombra cercanas",
      "Visibilidad desde las terrazas",
      "Materiales homologados",
      "Integrado en la naturaleza",
    ],
    capacity: "Ideal para niños de 3 a 12 años",
  },
  {
    slug: "karaoke",
    title: "Sala de Karaoke",
    headline: "Que no pare la música",
    shortDescription: "Sistema de sonido envolvente, micrófonos profesionales y pantalla para alargar la fiesta hasta la madrugada.",
    fullDescription: "El final perfecto para cualquier celebración en El Corrihuelo. Nuestro sistema de karaoke profesional está integrado en el salón principal, convirtiéndolo instantáneamente en una pista de baile y escenario. Cuenta con micrófonos inalámbricos, pantalla de seguimiento y un catálogo inmenso para que todos los invitados encuentren su canción.",
    heroImage: "/images/real/real-53.webp",
    gallery: [
      "/images/real/real-53.webp",
      "/images/real/real-54.webp",
      "/images/real/real-59.webp",
      "/images/real/real-57.webp",
    ],
    features: [
      "Sonido de alta fidelidad",
      "Micrófonos inalámbricos",
      "Pantalla grande de seguimiento",
      "Conexión Bluetooth para dispositivos",
      "Aislamiento acústico",
      "Iluminación de fiesta sincronizada",
    ],
    capacity: "Para todos los invitados del salón",
  },
  {
    slug: "ping-pong",
    title: "Mesa de Ping Pong",
    headline: "Competición y risas aseguradas",
    shortDescription: "Mesa de tenis de mesa profesional disponible para organizar pequeños torneos entre familiares o amigos.",
    fullDescription: "Las pausas entre la comida y la cena piden un poco de actividad. Nuestra mesa de ping pong profesional es uno de los puntos más concurridos en cualquier evento. Perfecta para jugar dobles, organizar un torneo exprés entre amigos o simplemente pasar un rato divertido quemando energía de forma saludable.",
    heroImage: "/images/real/real-2.webp",
    gallery: [
      "/images/real/real-2.webp",
      "/images/real/real-6.webp",
      "/images/real/real-1.webp",
      "/images/real/real-52.webp",
    ],
    features: [
      "Mesa de medidas oficiales",
      "Palas de alta calidad incluidas",
      "Pelotas de repuesto disponibles",
      "Opción de uso interior o exterior",
      "Ideal para torneos de grupo",
      "Fácil de montar y recoger",
    ],
    capacity: "2 a 4 jugadores simultáneos",
  },
  {
    slug: "futbolin",
    title: "Futbolín Profesional",
    headline: "Un clásico que nunca falla",
    shortDescription: "El auténtico futbolín de bar español para revivir las mejores partidas y crear un ambiente distendido.",
    fullDescription: "Ningún espacio de ocio está completo sin un buen futbolín. Hemos incorporado un futbolín español profesional, robusto y rápido, ideal para que tanto adultos como jóvenes compartan momentos de pura diversión. Es el rompehielos perfecto para eventos de empresa y el clásico indiscutible de los cumpleaños.",
    heroImage: "/images/real/real-57.webp",
    gallery: [
      "/images/real/real-57.webp",
      "/images/real/real-54.webp",
      "/images/real/real-59.webp",
      "/images/real/real-53.webp",
    ],
    features: [
      "Futbolín español clásico",
      "Jugadores de madera / metal",
      "Mesa robusta y nivelada",
      "Ubicado en zona de juegos",
      "Uso gratuito e ilimitado",
      "Perfecto para romper el hielo",
    ],
    capacity: "4 jugadores simultáneos",
  }
];

export type Installation = (typeof INSTALLATIONS_DATA)[0];
