export const INSTALLATIONS_DATA = [
  {
    slug: "piscina",
    title: "La Piscina",
    headline: "El oasis privado de la finca",
    shortDescription: "Piscina privada de agua cristalina rodeada de vegetación mediterránea. Solárium, tumbonas y zonas de sombra.",
    fullDescription: "Nuestra piscina privada es el corazón del verano en El Corrihuelo. Con dimensiones generosas para grupos grandes y rodeada de césped natural, es el espacio perfecto para refrescarse, relajarse y disfrutar de un día completo al sol murciano. El solárium cuenta con tumbonas y zonas de sombra para que cada momento sea confortable.",
    heroImage: "/images/terraza-piscina.jpg",
    gallery: [
      "/images/terraza-piscina.jpg",
      "/images/detalle-piscina.jpg",
      "/images/flores-entrada.jpg",
      "/images/hero-jardin.jpg",
    ],
    features: [
      "Uso exclusivo incluido en el precio",
      "Temporada cálida: mayo a octubre",
      "Zona de solárium con tumbonas",
      "Césped natural alrededor",
      "Zonas de sombra disponibles",
      "Duchas exteriores",
    ],
    capacity: "Hasta 80 personas",
  },
  {
    slug: "salon",
    title: "El Gran Salón",
    headline: "Elegancia y amplitud para tu celebración",
    shortDescription: "Salón diáfano con capacidad para grandes grupos, climatizado, con decoración rústica moderna y equipo de sonido.",
    fullDescription: "El Gran Salón de El Corrihuelo es el corazón de las celebraciones bajo techo. Con más de 120 m² diáfanos, se adapta a cualquier tipo de evento: cenas de gala, reuniones familiares, cumpleaños o bodas íntimas. Está completamente climatizado para asegurar el confort en cualquier época del año y equipado con sistema de sonido de alta fidelidad y karaoke.",
    heroImage: "/images/hero-salon.jpg",
    gallery: [
      "/images/hero-salon.jpg",
      "/images/salon-decorado.jpg",
      "/images/flores-salon.jpg",
      "/images/mesa-gourmet.jpg",
    ],
    features: [
      "Más de 120 m² diáfanos",
      "Climatización completa (frío/calor)",
      "Sistema de sonido profesional",
      "Iluminación regulable",
      "Decoración rústica moderna",
      "Mesas y sillas incluidas",
    ],
    capacity: "Hasta 100 personas sentadas",
  },
  {
    slug: "zona-gourmet",
    title: "Zona Gourmet",
    headline: "Todo equipado para la buena mesa",
    shortDescription: "Cocina interior completamente equipada, pensada tanto para particulares como para servicios de catering externos.",
    fullDescription: "En El Corrihuelo creemos que la buena mesa es parte esencial de cualquier celebración. Por eso hemos equipado nuestros espacios gastronómicos al máximo nivel. La cocina interior cuenta con electrodomésticos industriales, amplias zonas de trabajo y almacenamiento refrigerado suficiente para grandes eventos.",
    heroImage: "/images/mesa-gourmet.jpg",
    gallery: [
      "/images/mesa-gourmet.jpg",
      "/images/mesa-tapas.jpg",
      "/images/salon-decorado.jpg",
      "/images/flores-salon.jpg",
    ],
    features: [
      "Cocina interior equipada",
      "Neveras de gran capacidad",
      "Botelleros profesionales",
      "Compatible con servicio de catering",
      "Amplias encimeras de trabajo",
      "Utensilios básicos disponibles",
    ],
    capacity: "Servicio para hasta 100 personas",
  },
  {
    slug: "barbacoa",
    title: "Barbacoa Exterior",
    headline: "El auténtico sabor del fuego",
    shortDescription: "Amplia zona de asados exterior, perfecta para paellas gigantes, parrilladas de carne y reuniones informales al aire libre.",
    fullDescription: "No hay verdadera celebración rústica sin fuego. Nuestra espectacular zona de barbacoa exterior está diseñada para dar servicio a grupos grandes. Está equipada para preparar desde las tradicionales parrilladas de carne murcianas hasta paellas gigantes, todo ello bajo una cómoda zona cubierta que permite cocinar independientemente del clima.",
    heroImage: "/images/paella-grupo.jpg",
    gallery: [
      "/images/paella-grupo.jpg",
      "/images/paella2.jpg",
      "/images/mesa-tapas.jpg",
      "/images/grupo-exterior.jpg",
    ],
    features: [
      "Barbacoa de gran formato",
      "Zona techada para cocinar",
      "Ideal para asados y paellas",
      "Fregadero exterior integrado",
      "Mesas de apoyo cercanas",
      "Uso de leña/carbón permitido",
    ],
    capacity: "Uso simultáneo para grupos",
  },
  {
    slug: "jardines",
    title: "Los Jardines",
    headline: "Naturaleza y privacidad total",
    shortDescription: "Miles de metros cuadrados de jardines cuidados al milímetro. Vegetación autóctona, rincones de descanso y total intimidad.",
    fullDescription: "Los jardines de El Corrihuelo son un universo propio. Con miles de metros cuadrados de naturaleza mediterránea cuidada al detalle, ofrecen espacios diferenciados para cada momento de tu celebración: rincones íntimos para la sobremesa, zonas amplias para el cóctel de bienvenida, y caminos rodeados de flores para pasear al atardecer.",
    heroImage: "/images/hero-jardin.jpg",
    gallery: [
      "/images/hero-jardin.jpg",
      "/images/flores-entrada.jpg",
      "/images/grupo-exterior.jpg",
      "/images/baile-exterior.jpg",
    ],
    features: [
      "Más de 5.000 m² de parcela",
      "Vegetación autóctona madura",
      "Caminos adoquinados",
      "Iluminación exterior nocturna",
      "Rincones de descanso fotográficos",
      "Privacidad perimetral absoluta",
    ],
    capacity: "Sin límite (espacio exterior)",
  },
  {
    slug: "parque-infantil",
    title: "Parque Infantil",
    headline: "Diversión segura para los más pequeños",
    shortDescription: "Espacio delimitado y seguro con juegos al aire libre para que los niños disfruten mientras los adultos se relajan.",
    fullDescription: "Sabemos que en las celebraciones familiares el entretenimiento infantil es clave. Hemos destinado una zona del jardín a la creación de un parque infantil seguro y divertido. Situado de forma estratégica, permite a los padres tener a los niños a la vista desde los jardines y terrazas mientras disfrutan de la sobremesa.",
    heroImage: "/images/grupo-exterior.jpg",
    gallery: [
      "/images/grupo-exterior.jpg",
      "/images/baile-dia.jpg",
      "/images/hero-jardin.jpg",
      "/images/flores-entrada.jpg",
    ],
    features: [
      "Estructuras de juego exterior",
      "Suelo de seguridad/césped",
      "Zonas de sombra cercanas",
      "Visibilidad desde las terrazas",
      "Materiales homologados",
      "Integrado en la naturaleza",
    ],
    capacity: "Ideal para niños de 3 a 12 años",
  },
  {
    slug: "karaoke",
    title: "Sala de Karaoke",
    headline: "Que no pare la música",
    shortDescription: "Sistema de sonido envolvente, micrófonos profesionales y pantalla para alargar la fiesta hasta la madrugada.",
    fullDescription: "El final perfecto para cualquier celebración en El Corrihuelo. Nuestro sistema de karaoke profesional está integrado en el salón principal, convirtiéndolo instantáneamente en una pista de baile y escenario. Cuenta con micrófonos inalámbricos, pantalla de seguimiento y un catálogo inmenso para que todos los invitados encuentren su canción.",
    heroImage: "/images/baile-noche.jpg",
    gallery: [
      "/images/baile-noche.jpg",
      "/images/grupo-flamenca.jpg",
      "/images/guitarrista.jpg",
      "/images/pareja-flamenco.jpg",
    ],
    features: [
      "Sonido de alta fidelidad",
      "Micrófonos inalámbricos",
      "Pantalla grande de seguimiento",
      "Conexión Bluetooth para dispositivos",
      "Aislamiento acústico",
      "Iluminación de fiesta sincronizada",
    ],
    capacity: "Para todos los invitados del salón",
  },
  {
    slug: "ping-pong",
    title: "Mesa de Ping Pong",
    headline: "Competición y risas aseguradas",
    shortDescription: "Mesa de tenis de mesa profesional disponible para organizar pequeños torneos entre familiares o amigos.",
    fullDescription: "Las pausas entre la comida y la cena piden un poco de actividad. Nuestra mesa de ping pong profesional es uno de los puntos más concurridos en cualquier evento. Perfecta para jugar dobles, organizar un torneo exprés entre amigos o simplemente pasar un rato divertido quemando energía de forma saludable.",
    heroImage: "/images/baile-dia.jpg",
    gallery: [
      "/images/baile-dia.jpg",
      "/images/evento-grupo.jpg",
      "/images/grupo-exterior.jpg",
      "/images/terraza-piscina.jpg",
    ],
    features: [
      "Mesa de medidas oficiales",
      "Palas de alta calidad incluidas",
      "Pelotas de repuesto disponibles",
      "Opción de uso interior o exterior",
      "Ideal para torneos de grupo",
      "Fácil de montar y recoger",
    ],
    capacity: "2 a 4 jugadores simultáneos",
  },
  {
    slug: "futbolin",
    title: "Futbolín Profesional",
    headline: "Un clásico que nunca falla",
    shortDescription: "El auténtico futbolín de bar español para revivir las mejores partidas y crear un ambiente distendido.",
    fullDescription: "Ningún espacio de ocio está completo sin un buen futbolín. Hemos incorporado un futbolín español profesional, robusto y rápido, ideal para que tanto adultos como jóvenes compartan momentos de pura diversión. Es el rompehielos perfecto para eventos de empresa y el clásico indiscutible de los cumpleaños.",
    heroImage: "/images/evento-grupo.jpg",
    gallery: [
      "/images/evento-grupo.jpg",
      "/images/evento-grupo2.jpg",
      "/images/grupo-entrada.jpg",
      "/images/salon-decorado.jpg",
    ],
    features: [
      "Futbolín español clásico",
      "Jugadores de madera / metal",
      "Mesa robusta y nivelada",
      "Ubicado en zona de juegos",
      "Uso gratuito e ilimitado",
      "Perfecto para romper el hielo",
    ],
    capacity: "4 jugadores simultáneos",
  }
];

export type Installation = (typeof INSTALLATIONS_DATA)[0];
